CSV_SOURCE_PATH         = "csv_links_processing/data/pdf_links.csv"
CSV_DEST_PATH           = "csv_links_processing/data/filtered_pdf_links.csv"
CSV_STATS_PATH          = "csv_links_processing/data/stats.csv"
CSV_EVALUATION_PATH     = "csv_links_processing/evaluation_tests/data/01_40.csv"
CSV_EVALUATION_FOLDER   = "csv_links_processing/evaluation_tests/data/"
OCR_PDF_PATH            = "pdf_ocr/data/pdf"
TOKENS_PATH             = "tokens.txt"